### PR TITLE
fig3 nnls plots

### PR DESCRIPTION
**Pull request by ajtsao1**
Here are the nnls plots using the averages of the 4 data points for each mixture, for figs. 3A and 3B.

### CODE REVIEW

**Comment by ajtsao1** [comment]
@aarmey I wasn't sure what's the best way to move the code from the notebook into the figures folder, so I roughly followed what was done in the Systems Serology repository. Now, there is a common file and a figure 1 file but let me know if you think there's a better way to organize this.

**Review by aarmey — CHANGES_REQUESTED** [review]
Can you make it so that the notebook calls and shows the output of `makeFig1()`? (Rather than duplicating all the code.) Then also give you notebook a descriptive name. After that this should be all set for now.

**Comment by ajtsao1** [comment]
@aarmey Got it. Good thing you suggested that because I figured out that I didn't change the path for loading the csv files when I moved the code into the figures - that’s fixed now. I also got rid of the duplicated code in the notebook.

**Review by aarmey — APPROVED** [review]
Ready to merge.

**Pull request merged**
