### PR TITLE
compare inferred x

### PR DESCRIPTION
**Pull request by ajtsao1**
@aarmey Here is what I did for the 4th thing you suggested on Slack. I’m comparing the inferred x from fig1 (only using anti-D data) with the inferred x from using the concatenated anti-D and anti-TNP data.

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
Excellent! Can you concat the anti-D matrix twice, since these are both anti-D in Fig. 3? Then this can go in a new figure file instead of a notebook.

**Comment by ajtsao1** [comment]
@aarmey Here is the python file called figure3 (and the notebook deleted). For the anti-D only, I inferred x using the doubled anti-D matrix. Is this what you meant by concat. D twice? Or did you mean to concat. D twice instead of concatenating D with TNP?

**Comment by aarmey** [comment]
This is what I mean—double anti-D. Change the figure labels then this might be ready.

**Comment by ajtsao1** [comment]
@aarmey Okay, I changed the labels here for the doubled antiD.

**Review by aarmey — APPROVED** [review]
Ready to merge.

**Pull request merged**
