### PR TITLE
new figure 3

### PR DESCRIPTION
**Pull request by evahunter**
Was having some trouble with the paths for some reason even though they were working for sumedha ... will see if this worked.

### CODE REVIEW

**Comment by aarmey** [comment]
This looks reasonable. You should just replace figure3.py. After that you can run `make output/figure3.svg` to build the figure.

**Review by aarmey — CHANGES_REQUESTED** [review]
This looks good. Just need to add uncertainty.

**Comment by evahunter** [comment]
the error bars I added aren't centered around the points and I am not sure why - to have consistent units I used to 33rd and 66th percentile of the data and put it through the PCA transform.

**Comment by aarmey** [comment]
Sorry if I missed it before, but you shouldn't need to run PCA here. The MCMC samples are already in PCA space. You just need to directly plot the factors themselves.

**Comment by evahunter** [comment]
I made it so that the loadings shows all 12 of the components, I'm still having some trouble with the error bars.

**Comment by aarmey** [comment]
What sort of trouble?

**Comment by aarmey** [comment]
Just removed PCA. This is ready—will merge assuming it builds.

**Pull request merged**
