### PR TITLE
Mixtures heatmap and correlation matrix

### PR DESCRIPTION
**Pull request by sumedha-k**
@aarmey This branch contains figure 4 and figure 5 which are the heatmap and correlation coefficient matrix respectively. I was able to merge main into this branch and resolved conflicts. The only issue we might have is the Evie's has the swarm plots on her branch as figure 4. I'm thinking we probably need to wait until that is merged before we merge this.

### CODE REVIEW

**Comment by sumedha-k** [comment]
Also I initially updates the figure 2 axes in this branch (commit 676c1cd), but I removed it once I merged main in (commit 772b30b). I'll create a new branch to update figure 2.

**Comment by sumedha-k** [comment]
We'll also probably need to change the colors. As of right now the two plots look like this:
image
image

**Review by aarmey — CHANGES_REQUESTED** [review]
Please resolve the new merge conflicts and then re-tag me.

**Comment by sumedha-k** [comment]
@aarmey  done

**Review by aarmey — APPROVED** [review]
Good to merge!

**Pull request merged**
